#!/bin/bash
set -eu
# This script starts the application.  It is used by the cucumber tests (under-test.rb).

BASE_DIR="$( dirname "$0" )"

jar="$( echo "$BASE_DIR"/target/componentd-*-shaded.jar )"
exec exec java -ea -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar "$jar" "$@"